### ISSUE TITLE
doc.body is null

### ISSUE THREAD

**Issue by Spone** [nico3333fr/van11y-accessible-modal-tooltip-aria#3]
Hello,

I'm using npm and webpack.

I import the lib with:

    import van11yAccessibleModalTooltipAria from "van11y-accessible-modal-tooltip-aria/src/van11y-accessible-modal-tooltip-aria.es6.js";

I have this error if Firefox dev tools:

    TypeError: doc.body is null

I would like the library to do nothing automatically, so I can attach it to DOM elements when I want.

Can you help?

**Comment by nico3333fr** [comment]
Hello,

I don't know webpack, I hope we will find anyway :) 

If you import with `import van11yAccessibleModalTooltipAria from "van11y-accessible-modal-tooltip-aria/dist/van11y-accessible-modal-tooltip-aria.js";` 

Does it work ?

**Comment by Spone** [comment]
Thanks for your help. I have the same result with your code.

I think there should be a condition on `doc.body` so it does not break if the script doesn't have access to `doc.body` when it runs.

**Comment by tdd** [comment]
@nico3333fr @Spone seems to me this is 100% unrelated to Webpack: the source code simply:

1. Assumes it's run in a webpage context (which it is, I guess).
2. Auto-inits at load (bad practice), therefore needs `document.body` to be initialized, which means the script containing that module cannot be in `<head>`, it has to be loaded later in the doc than the `<body>` opening tag.

(*Incidentally, this module exports nothing, so you don't need to `import X from 'path'` (X will be `undefined`, there is no `default` export), just `import 'path'`.*)

My advice to @nico3333fr: don't make your modules auto-init, export an init function (default and/or named) and have people call it when they see fit. If you *must* auto-init, at least wait for `DOMContentLoaded` to trigger, so you can safely attach to `document.body`.

**Comment by Spone** [comment]
Thanks Christophe, you're right it's not related to Webpack, but it makes using the script with Webpack pretty hard, as it doesn't behave like most libraries. I should be able to autoload it when I know my document is ready.

**Comment by nico3333fr** [comment]
Thanks @tdd and @Spone => Basically (sorry, I'm a noob in JS), I thought this part:

```
const onLoad = () => {
        attach();
        document.removeEventListener('DOMContentLoaded', onLoad);
    }
    document.addEventListener('DOMContentLoaded', onLoad);
window.van11yAccessibleModalTooltipAria = attach;
```
should be enough. Anyway, how do I set it up? Is this

```
window.van11yAccessibleModalTooltipAria = attach;

const onLoad = () => {
        van11yAccessibleModalTooltipAria();
        document.removeEventListener('DOMContentLoaded', onLoad);
    }

const initVan11yAccessibleModalTooltipAria = () => {
  document.addEventListener('DOMContentLoaded', onLoad);
};

export default initVan11yAccessibleModalTooltipAria;
```
Ok?

(sorry if these are stupid questions)

**Comment by tdd** [comment]
Hey @nico3333fr nope, the trouble is your keyboard-binding code:

https://github.com/nico3333fr/van11y-accessible-modal-tooltip-aria/blob/master/src/van11y-accessible-modal-tooltip-aria.es6.js#L219-L223

It **is not within `attach`**, but triggered at module-load time. The whole keyboard-binding thing should happen within your attach function somehow. Then loading it from `DOMContentLoaded` is good enough.

**Comment by tdd** [comment]
(btw you use a `src/` dir with "ES6" source, but it's *far* from using ES6 idiomatically; tons of ES5-style code in there and needless verbiage; I can only hope you'll manage to attend one of my ES classes someday 😉 to spruce this up!)

**Comment by nico3333fr** [comment]
Ok, much clear, got it!

For ES6 source, yes, I've learned by myself, and tried to keep a compatibility for IE9 with my poor knowledge, I would REALLY like to attend your ES classes :)

**Comment by nico3333fr** [comment]
Hi @Spone could you test if everything is okay, just before I merge the fix ?

https://github.com/nico3333fr/van11y-accessible-modal-tooltip-aria/pull/4

Kind regards,
Nicolas

**Comment by nico3333fr** [comment]
Okay, I merge. Keep me informed if there is still an issue ;)
